image: Visual Studio 2019
environment:
  JAVA_HOME: C:\Program Files\Java\jdk15
install:
- cmd: set PATH=%PATH%;C:\Program Files\Java\jdk15\bin
build_script:
- cmd: mvn package
artifacts:
- path: target/CayoPericoHeistAssistant*.msi
  name: installer
- path: target/CayoPericoHeistAssistant.zip
  name: archive